# Import the theme
theme: jekyll-theme-chirpy

lang: pt-BR

timezone: America/Sao_Paulo # https://kevinnovak.github.io/Time-Zone-Picker

title: Pelicano
tagline: Leia com caridade :)
description: >-
  Explore textos católicos inspiradores e reflexivos em nosso blog, dedicado ao crescimento espiritual e à fé cristã. Descubra ensinamentos, tradições e insights que podem iluminar sua jornada espiritual.

url: "https://o-pelicano.com"

github:
  username: smrsassa

social:
  name: Samuel Mayer Rufino
  email: samrufino13@gmail.com
  links:
    - https://www.instagram.com/sam_rufino/
    - https://github.com/smrsassa
    - https://www.linkedin.com/in/samuel-mayer-302a65193/

google_site_verification: # fill in to your verification string

goatcounter:
  id: o-pelicano

theme_mode: dark # [light|dark]

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/pelicano.png
favicon: /assets/img/favicons/favicon.ico
head_icons:
  favicon: /assets/img/favicons/favicon.ico

# boolean type, the global switch for TOC in posts.
toc: true

pwa:
  enabled: true # the option for PWA feature

paginate: 10

baseurl: "" # The base URL of your site

# ------------ The following options are not recommended to be modified ------------------
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tags:
    output: false
  categories:
    output: false
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
